# SPDX-FileCopyrightText: 2024 Roy Wright
#
# SPDX-License-Identifier: MIT

# MkDocs markdown documentation configuration with material theme and auto API document generation.
# scripts/gen_ref_pages.py is required for auto API generation.dev_addr
# Also docs/index.md is a symbolic link to the project's README.md

site_name: Version Bumper
site_author: Roy Wright
copyright: 2024 by Roy Wright
repo_name: version_bumper
repo_url: https://github.com/royw/version_bumper
docs_dir: docs
site_dir: site

theme:
  name: material
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  locale: en
  language: en
  font: false
  color_mode: auto
  use_color_mode_toggle: true
  highlightjs: true
  hljs_languages:
    - yaml

plugins:
  - search
  - gen-files:
      scripts:
        - scripts/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - mkdocstrings:
      default_handler: python
      enable_inventory: false
      handlers:
        python:
          paths: [src]
          load_external_modules: false

nav:
  - About: "index.md"
  - Development Environment: "DEV-README.md"
  # rest of the navigation...
  # defer to gen-files + literate-nav
  - Code Reference: reference/
  # rest of the navigation...
